import React, { useMemo, useRef, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import {
  Activity, ArrowLeft, ArrowRight, Bell, Brain, Check, ChevronRight, CircleHelp,
  Clock3, Eye, EyeOff, FileText, FlaskConical, History, LayoutDashboard, LogIn,
  Mail, Menu, MessageCircle, Plus, Search, ScanLine, Settings, ShieldCheck,
  Sparkles, UploadCloud, UserPlus, X, LockKeyhole, SlidersHorizontal
} from "lucide-react";

const steps = [
  { n: "01", title: "Upload", text: "Add a brain MRI scan." },
  { n: "02", title: "Analyze", text: "Classify the scan with AI." },
  { n: "03", title: "Explain", text: "See what influenced the model." },
  { n: "04", title: "Report", text: "Turn the result into a clear report." },
];

const capabilities = [
  { icon: Brain, title: "Brain tumor classification", text: "Analyze an MRI and return the model's predicted class and confidence." },
  { icon: ScanLine, title: "Explainable AI", text: "Visualize model attention with Grad-CAM so the output is easier to understand." },
  { icon: Sparkles, title: "GenAI explanations", text: "Translate technical model output into human-readable language." },
  { icon: Activity, title: "Agentic workflow", text: "Coordinate analysis, explanation and reporting as one connected workflow." },
];

const cases = [
  { id: "BX-2048", file: "brain_scan_2048.jpg", result: "Glioma", confidence: "94.2%", status: "Completed", date: "Today · 10:42" },
  { id: "BX-2044", file: "mri_case_044.png", result: "Meningioma", confidence: "91.7%", status: "Completed", date: "Yesterday · 16:18" },
  { id: "BX-2039", file: "patient_scan_039.jpeg", result: "No tumor", confidence: "88.4%", status: "Completed", date: "Sep 29 · 12:06" },
  { id: "BX-2035", file: "scan_followup_035.jpg", result: "Pituitary", confidence: "86.1%", status: "Completed", date: "Sep 27 · 09:31" },
  { id: "BX-2029", file: "brain_mri_029.png", result: "Glioma", confidence: "92.8%", status: "Completed", date: "Sep 25 · 18:03" },
];

function Logo({ light = false }) {
  return <div className={"brand " + (light ? "brand-light" : "")}><span className="brand-mark"><Brain size={18} strokeWidth={2.2} /></span><span>Brain<span className="brand-accent">X</span> AI</span></div>;
}

function Landing({ onStart, onLogin, onBrowse }) {
  const [menuOpen, setMenuOpen] = useState(false);
  return <div className="landing">
    <nav className="landing-nav container">
      <Logo />
      <div className={"nav-links " + (menuOpen ? "open" : "")}>
        <a href="#how">How it works</a><a href="#capabilities">Capabilities</a><a href="#trust">Trust & limits</a>
        <button className="nav-text" onClick={onBrowse}>Browse cases</button>
        <button className="nav-signin" onClick={onLogin}>Sign in</button>
      </div>
      <button className="mobile-menu" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu">{menuOpen ? <X size={21} /> : <Menu size={21} />}</button>
    </nav>
    <main>
      <section className="hero container">
        <div className="hero-copy">
          <div className="eyebrow"><span className="status-dot" /> AI BRAIN MRI ANALYSIS COPILOT</div>
          <h1>See the scan.<br /><span>Understand the AI.</span></h1>
          <p>BrainX connects MRI classification, explainable AI and Generative AI into one guided analysis workflow — from scan to understandable report.</p>
          <div className="hero-actions"><button className="btn btn-primary btn-lg" onClick={onStart}>Start analysis <ArrowRight size={17} /></button><button className="btn btn-secondary btn-lg" onClick={onBrowse}>Browse cases</button></div>
          <div className="hero-note"><ShieldCheck size={15} /> Preliminary AI analysis · Not a medical diagnosis</div>
        </div>
        <div className="hero-visual"><div className="visual-glow" /><div className="scan-card">
          <div className="scan-topbar"><span><span className="mini-live" /> LIVE ANALYSIS PREVIEW</span><span>BX-2048</span></div>
          <div className="brain-art"><div className="brain-ring ring-one" /><div className="brain-ring ring-two" /><div className="brain-core"><div className="brain-half left" /><div className="brain-half right" /><div className="attention attention-one" /><div className="attention attention-two" /></div><div className="scan-line" /><div className="axis-label x">R</div><div className="axis-label y">L</div></div>
          <div className="scan-footer"><div><span className="label">MODEL OUTPUT</span><strong>Glioma</strong></div><div className="confidence"><span>94.2%</span><div className="confidence-bar"><i /></div></div></div>
        </div><div className="floating-chip chip-analysis"><Activity size={14} /> Analysis complete</div><div className="floating-chip chip-xai"><ScanLine size={14} /> Grad-CAM ready</div></div>
      </section>
      <section className="trust-strip"><div className="container trust-inner"><span>ONE WORKSPACE</span><i /><span>COMPUTER VISION</span><i /><span>EXPLAINABLE AI</span><i /><span>GENAI</span><i /><span>AGENTIC WORKFLOW</span></div></section>
      <section className="workflow section container" id="how"><div className="section-heading"><div><span className="section-kicker">HOW BRAINX WORKS</span><h2>One scan. Four connected stages.</h2></div><p>The interface keeps every stage visible, so the intelligence behind the result never feels like a black box.</p></div><div className="workflow-grid">{steps.map((step, i) => <motion.div key={step.n} className="workflow-card" initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * .07 }}><span className="step-number">{step.n}</span><div className="step-icon">{i === 0 ? <UploadCloud /> : i === 1 ? <FlaskConical /> : i === 2 ? <ScanLine /> : <FileText />}</div><h3>{step.title}</h3><p>{step.text}</p>{i < 3 && <ChevronRight className="workflow-arrow" size={18} />}</motion.div>)}</div></section>
      <section className="capabilities section" id="capabilities"><div className="container"><div className="section-heading"><div><span className="section-kicker">BUILT FOR UNDERSTANDING</span><h2>More than a prediction.</h2></div><p>BrainX brings computer vision, XAI, GenAI and agentic components together into one experience.</p></div><div className="cap-grid">{capabilities.map((item, i) => { const Icon = item.icon; return <motion.article className="cap-card" key={item.title} whileHover={{ y: -4 }} transition={{ duration: .2 }}><div className="cap-icon"><Icon size={19} /></div><span className="cap-index">0{i + 1}</span><h3>{item.title}</h3><p>{item.text}</p><ArrowRight size={17} className="cap-arrow" /></motion.article> })}</div></div></section>
      <section className="trust-section section container" id="trust"><div className="trust-panel"><div className="trust-icon"><ShieldCheck size={22} /></div><div><span className="section-kicker">DESIGNED WITH LIMITS IN MIND</span><h2>Clear about what the AI can — and cannot — tell you.</h2><p>BrainX presents model outputs, confidence and explainability together, while clearly separating AI assistance from clinical diagnosis.</p></div><button className="text-button" onClick={onStart}>Explore demo <ArrowRight size={16} /></button></div></section>
      <section className="final-cta container"><div><span className="section-kicker">READY TO ANALYZE?</span><h2>Turn an MRI into an understandable AI report.</h2></div><button className="btn btn-primary btn-lg" onClick={onStart}>Open BrainX <ArrowRight size={17} /></button></section>
    </main>
    <footer className="landing-footer"><div className="container footer-inner"><Logo /><span>AI Brain MRI Analysis Copilot</span><span>Preliminary AI analysis · Not a medical diagnosis</span></div></footer>
  </div>;
}

function AuthShell({ mode, onModeChange, onSuccess, onBack }) {
  const isLogin = mode === "login";
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirm, setShowConfirm] = useState(false);
  const [forgot, setForgot] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [error, setError] = useState("");
  const [form, setForm] = useState({ name: "", email: "", password: "", confirm: "" });
  const update = (key, value) => setForm(prev => ({ ...prev, [key]: value }));

  if (forgot) return <div className="auth-page"><div className="auth-shell"><div className="auth-brand"><Logo /></div><div className="auth-card"><button className="back-link" onClick={() => setForgot(false)}><ArrowLeft size={15} /> Back to sign in</button><div className="auth-icon"><Mail size={21} /></div><span className="section-kicker">ACCOUNT RECOVERY</span><h1>Reset your password.</h1><p>Enter your email and the backend will send the password-reset flow once authentication is connected.</p>{submitted ? <div className="success-box"><Check size={17} /><span>If this email exists, a reset link will be sent.</span></div> : <form onSubmit={e => { e.preventDefault(); setSubmitted(true); }}><label>Email address<input type="email" required placeholder="you@example.com" value={form.email} onChange={e => update("email", e.target.value)} /></label><button className="btn btn-primary auth-submit" type="submit">Send reset link <ArrowRight size={16} /></button></form>}<div className="auth-footer"><button onClick={onBack}>Return to BrainX</button></div></div><AuthDisclaimer /></div></div>;

  const submit = e => { e.preventDefault(); setError(""); if (!isLogin && form.password !== form.confirm) { setError("Passwords do not match."); return; } setSubmitted(true); setTimeout(onSuccess, 250); };
  return <div className="auth-page"><div className="auth-shell"><div className="auth-brand"><Logo /></div><div className="auth-card"><button className="back-link" onClick={onBack}><ArrowLeft size={15} /> Back to landing</button><div className="auth-icon">{isLogin ? <LogIn size={21} /> : <UserPlus size={21} />}</div><span className="section-kicker">{isLogin ? "WELCOME BACK" : "CREATE YOUR WORKSPACE"}</span><h1>{isLogin ? "Sign in to BrainX." : "Create your BrainX account."}</h1><p>{isLogin ? "Continue to your analysis workspace." : "Set up your workspace before connecting the real authentication API."}</p>
    <form onSubmit={submit}>{!isLogin && <label>Full name<input required autoComplete="name" placeholder="Your name" value={form.name} onChange={e => update("name", e.target.value)} /></label>}<label>Email address<input required type="email" autoComplete="email" placeholder="you@example.com" value={form.email} onChange={e => update("email", e.target.value)} /></label><label>Password<div className="password-wrap"><input required minLength={8} type={showPassword ? "text" : "password"} autoComplete={isLogin ? "current-password" : "new-password"} placeholder="At least 8 characters" value={form.password} onChange={e => update("password", e.target.value)} /><button type="button" onClick={() => setShowPassword(!showPassword)} aria-label="Toggle password visibility">{showPassword ? <EyeOff size={16} /> : <Eye size={16} />}</button></div></label>{!isLogin && <label>Confirm password<div className="password-wrap"><input required minLength={8} type={showConfirm ? "text" : "password"} autoComplete="new-password" placeholder="Repeat your password" value={form.confirm} onChange={e => update("confirm", e.target.value)} /><button type="button" onClick={() => setShowConfirm(!showConfirm)}>{showConfirm ? <EyeOff size={16} /> : <Eye size={16} />}</button></div></label>}{error && <div className="form-error">{error}</div>}<button className="btn btn-primary auth-submit" type="submit">{isLogin ? "Sign in" : "Create account"} <ArrowRight size={16} /></button></form>
    {isLogin && <button className="forgot-link" onClick={() => setForgot(true)}>Forgot password?</button>}<div className="auth-divider"><span>or</span></div><div className="auth-switch">{isLogin ? "New to BrainX?" : "Already have an account?"}<button onClick={() => { setSubmitted(false); onModeChange(isLogin ? "signup" : "login"); }}>{isLogin ? "Create account" : "Sign in"}</button></div><div className="demo-auth-note"><LockKeyhole size={14} /><span>Frontend demo mode. Credentials will be validated by the backend once its auth API is connected.</span></div></div><AuthDisclaimer /></div></div>;
}

function AuthDisclaimer() { return <div className="auth-disclaimer"><ShieldCheck size={14} /> Secure authentication and data handling will be provided by the project backend.</div>; }

function Sidebar({ active, setActive, mobileOpen, setMobileOpen }) {
  const nav = [{ id: "dashboard", label: "Overview", icon: LayoutDashboard }, { id: "new", label: "New analysis", icon: Plus }, { id: "browse", label: "Browse cases", icon: Search }, { id: "history", label: "Analysis history", icon: History }, { id: "reports", label: "Reports", icon: FileText }, { id: "assistant", label: "AI assistant", icon: MessageCircle }];
  return <><AnimatePresence>{mobileOpen && <motion.div className="drawer-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={() => setMobileOpen(false)} />}</AnimatePresence><aside className={"sidebar " + (mobileOpen ? "mobile-open" : "")}><div className="sidebar-top"><Logo /><button className="close-sidebar" onClick={() => setMobileOpen(false)}><X size={18} /></button></div><button className="new-analysis-btn" onClick={() => { setActive("new"); setMobileOpen(false); }}><Plus size={17} /> New analysis</button><div className="sidebar-label">WORKSPACE</div><nav>{nav.map(item => { const Icon = item.icon; return <button key={item.id} className={active === item.id ? "active" : ""} onClick={() => { setActive(item.id); setMobileOpen(false); }}><Icon size={17} />{item.label}</button>; })}</nav><div className="sidebar-label sidebar-bottom-label">ACCOUNT</div><nav><button onClick={() => { setActive("settings"); setMobileOpen(false); }}><Settings size={17} />Settings</button><button onClick={() => { setActive("help"); setMobileOpen(false); }}><CircleHelp size={17} />Help & limits</button></nav><div className="sidebar-user"><div className="avatar">W</div><div><strong>Wajeeha</strong><span>Research workspace</span></div></div></aside></>;
}

function Header({ onMenu, onBrowse, onNotifications }) { return <header className="app-header"><button className="mobile-header-menu" onClick={onMenu}><Menu size={20} /></button><div className="header-search" onClick={onBrowse}><Search size={16} /><span>Search analyses, reports, cases...</span><kbd>⌘ K</kbd></div><div className="header-right"><button className="icon-button" onClick={onNotifications} aria-label="Notifications"><Bell size={17} /><span className="notification-dot" /></button><span className="system-status"><span /> System ready</span><div className="header-avatar">W</div></div></header>; }

function Dashboard({ setActive }) {
  const recent = cases.slice(0, 3);
  return <div className="dashboard-page"><div className="dashboard-hero"><div><span className="section-kicker">BRAINX WORKSPACE</span><h2>Your analysis workspace.</h2><p>Upload an MRI, follow the agentic workflow and review the generated explanation in one place.</p><div className="hero-actions"><button className="btn btn-primary" onClick={() => setActive("new")}>Start new analysis <ArrowRight size={16} /></button><button className="btn btn-secondary" onClick={() => setActive("browse")}>Browse cases</button></div></div><div className="dashboard-orbit"><div className="orbit-ring ring-a" /><div className="orbit-ring ring-b" /><div className="orbit-center"><Brain size={43} /></div><span className="orbit-node node-1"><ScanLine size={15} /></span><span className="orbit-node node-2"><Sparkles size={15} /></span><span className="orbit-node node-3"><FileText size={15} /></span></div></div>
    <section className="stats-row"><div className="stat-card"><div className="stat-icon blue"><ScanLine size={18} /></div><div><span>Analyses</span><strong>12</strong></div><small>+3 this week</small></div><div className="stat-card"><div className="stat-icon teal"><FileText size={18} /></div><div><span>Reports</span><strong>8</strong></div><small>67% of analyses</small></div><div className="stat-card"><div className="stat-icon slate"><Clock3 size={18} /></div><div><span>Last analysis</span><strong>2h</strong></div><small>Today at 10:42</small></div></section>
    <section className="dashboard-grid"><div className="recent-panel panel"><div className="panel-header"><div><span className="section-kicker">RECENT</span><h3>Analysis history</h3></div><button className="text-button" onClick={() => setActive("history")}>View all <ArrowRight size={15} /></button></div><div className="analysis-list">{recent.map(r => <button className="analysis-row" key={r.file} onClick={() => setActive("results")}><div className="file-thumb"><Brain size={20} /></div><div className="analysis-main"><strong>{r.file}</strong><span>{r.date}</span></div><div className="result-pill"><span />{r.result}</div><div className="confidence-small">{r.confidence}</div><ChevronRight className="row-arrow" size={17} /></button>)}</div></div><div className="workflow-panel panel"><div className="panel-header"><div><span className="section-kicker">WORKFLOW</span><h3>What happens next?</h3></div></div><div className="mini-flow">{steps.map((s, i) => <div className="mini-flow-row" key={s.n}><span className={"mini-step " + (i === 0 ? "current" : "")}>{i === 0 ? <Check size={14} /> : s.n}</span><div><strong>{s.title}</strong><span>{s.text}</span></div>{i < 3 && <div className="mini-connector" />}</div>)}</div></div></section><div className="dashboard-disclaimer"><ShieldCheck size={15} /> BrainX provides preliminary AI-based analysis and should not be treated as a medical diagnosis.</div></div>;
}

function Browse({ setActive }) {
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState("All");
  const filtered = useMemo(() => cases.filter(c => (filter === "All" || c.result === filter) && (c.file.toLowerCase().includes(query.toLowerCase()) || c.id.toLowerCase().includes(query.toLowerCase()) || c.result.toLowerCase().includes(query.toLowerCase()))), [query, filter]);
  const filters = ["All", "Glioma", "Meningioma", "Pituitary", "No tumor"];
  return <div className="browse-page"><div className="page-intro"><div><span className="section-kicker">CASE LIBRARY</span><h1>Browse analyses.</h1><p>Search and review previous AI analysis records available in your workspace.</p></div><button className="btn btn-primary" onClick={() => setActive("new")}>New analysis <Plus size={16} /></button></div><div className="browse-toolbar"><div className="browse-search"><Search size={17} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search by case ID, filename or result..." /></div><div className="filter-row"><SlidersHorizontal size={15} />{filters.map(f => <button key={f} className={filter === f ? "selected" : ""} onClick={() => setFilter(f)}>{f}</button>)}</div></div><div className="browse-meta"><span>{filtered.length} case{filtered.length !== 1 ? "s" : ""}</span><span>Demo workspace data</span></div><div className="case-grid">{filtered.map((c, i) => <motion.article className="case-card" key={c.id} layout initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * .03 }}><div className="case-preview"><Brain size={39} /><span>{c.id}</span></div><div className="case-body"><div className="case-top"><span className="status-tag"><Check size={12} /> {c.status}</span><span>{c.date}</span></div><h3>{c.file}</h3><div className="case-result"><div><span>Prediction</span><strong>{c.result}</strong></div><div><span>Confidence</span><strong>{c.confidence}</strong></div></div><button className="case-open" onClick={() => setActive("results")}>Open analysis <ArrowRight size={15} /></button></div></motion.article>)}</div>{filtered.length === 0 && <div className="empty-state"><Search size={22} /><h3>No matching cases</h3><p>Try another search term or filter.</p></div>}<div className="demo-preview-note"><ShieldCheck size={16} /><span><strong>Backend handoff:</strong> this screen is ready for a cases API. Replace the demo <code>cases</code> array with the team's authenticated API response when available.</span></div></div>;
}

function NewAnalysis({ setActive }) {
  const inputRef = useRef(null); const [file, setFile] = useState(null);
  const choose = e => { const selected = e.target.files?.[0]; if (selected) setFile(selected); };
  return <div className="simple-page"><span className="section-kicker">NEW ANALYSIS</span><h1>Upload a brain MRI.</h1><p className="page-subtitle">Start the BrainX workflow with a scan you are authorized to analyze.</p><input ref={inputRef} type="file" accept=".jpg,.jpeg,.png,.webp" hidden onChange={choose} /><div className={"upload-card " + (file ? "has-file" : "")} onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); const dropped = e.dataTransfer.files?.[0]; if (dropped) setFile(dropped); }}><div className="upload-icon">{file ? <Check size={25} /> : <UploadCloud size={25} />}</div>{file ? <><h2>{file.name}</h2><p>{(file.size / 1024 / 1024).toFixed(2)} MB · Ready for analysis</p><div className="upload-actions"><button className="btn btn-primary" onClick={() => setActive("processing")}>Analyze scan <ArrowRight size={16} /></button><button className="btn btn-secondary" onClick={() => setFile(null)}>Choose another</button></div></> : <><h2>Drop your MRI here</h2><p>or browse files from your device</p><button className="btn btn-primary" onClick={() => inputRef.current?.click()}>Browse files</button></>}<span className="upload-meta">JPG · JPEG · PNG · WEBP · File limits depend on backend configuration</span></div><div className="demo-preview-note"><Sparkles size={16} /><span><strong>Frontend upload:</strong> the selected file is captured locally for now. The backend member will connect the upload to the MRI processing endpoint.</span></div></div>;
}

function Processing({ setActive }) { const stages = ["MRI received", "AI model analyzing image", "Tumor classification", "Grad-CAM generation", "GenAI explanation", "Report preparation"]; return <div className="processing-page"><span className="section-kicker">AGENTIC WORKFLOW</span><h1>BrainX is analyzing the scan.</h1><p className="page-subtitle">The timeline makes each stage of the workflow visible.</p><div className="processing-layout"><div className="processing-card">{stages.map((s, i) => <div className={"process-step " + (i < 3 ? "done" : i === 3 ? "active" : "")} key={s}><span className="process-dot">{i < 3 ? <Check size={13} /> : i === 3 ? <span className="pulse" /> : i + 1}</span><div><strong>{s}</strong><span>{i < 3 ? "Completed" : i === 3 ? "Processing now..." : "Waiting"}</span></div></div>)}</div><div className="processing-info"><div className="processing-orb"><Brain size={42} /></div><h3>Agentic analysis</h3><p>Classification, explainability and GenAI interpretation are coordinated as one workflow.</p><button className="text-button" onClick={() => setActive("results")}>Preview results <ArrowRight size={15} /></button></div></div></div>; }

function Results({ setActive }) { return <div className="results-page"><div className="page-intro"><div><span className="section-kicker">ANALYSIS / BX-2048</span><h1>Analysis results</h1><p>Illustrative demo result — connect these fields to the actual model response.</p></div><span className="complete-badge"><Check size={14} /> Completed</span></div><div className="prediction-card"><div><span className="label">MODEL PREDICTION</span><h2>Glioma</h2><p>Predicted class</p></div><div className="prediction-confidence"><span>Model confidence</span><strong>94.2%</strong><div><i /></div><small>Model confidence, not clinical probability.</small></div><div className="prediction-actions"><button className="btn btn-primary" onClick={() => setActive("reports")}>Generate report <FileText size={16} /></button><button className="btn btn-secondary" onClick={() => setActive("assistant")}>Ask AI <MessageCircle size={16} /></button></div></div><div className="result-images"><div className="result-image-card"><div className="result-image-header"><span>ORIGINAL MRI</span><button>Open</button></div><div className="fake-mri"><Brain size={74} /></div></div><div className="result-image-card"><div className="result-image-header"><span>GRAD-CAM OVERLAY</span><button>Open</button></div><div className="fake-mri heat"><Brain size={74} /></div></div></div><div className="explanation-card"><div className="explanation-icon"><Sparkles size={18} /></div><div><span className="section-kicker">GENAI EXPLANATION</span><h3>What does this result mean?</h3><p>The classification model assigned this scan to the Glioma class. The accompanying visualization can help show image regions that influenced the model's output. This result requires review by a qualified medical professional.</p><button className="text-button" onClick={() => setActive("assistant")}>Ask about this result <ArrowRight size={15} /></button></div></div><div className="result-warning"><ShieldCheck size={16} /><span><strong>Important:</strong> BrainX provides preliminary AI-based analysis and is not a medical diagnosis.</span></div></div>; }

function Placeholder({ active, setActive }) { const titles = { history: "Analysis history", reports: "AI reports", assistant: "AI assistant", settings: "Workspace settings", help: "Help & limits" }; const icons = { history: History, reports: FileText, assistant: MessageCircle, settings: Settings, help: CircleHelp }; const Icon = icons[active] || History; return <div className="simple-page placeholder-page"><div className="placeholder-icon"><Icon size={26} /></div><span className="section-kicker">BRAINX WORKSPACE</span><h1>{titles[active]}</h1><p className="page-subtitle">This screen is scaffolded and ready for the corresponding backend integration.</p>{active === "assistant" && <button className="btn btn-primary" onClick={() => setActive("results")}>Open current analysis</button>}{active === "reports" && <button className="btn btn-primary" onClick={() => setActive("results")}>View demo report source</button>}</div>; }

function AppShell({ onExit }) {
  const [active, setActive] = useState("dashboard"); const [mobileOpen, setMobileOpen] = useState(false); const [notice, setNotice] = useState(false);
  const content = { dashboard: <Dashboard setActive={setActive} />, new: <NewAnalysis setActive={setActive} />, browse: <Browse setActive={setActive} />, processing: <Processing setActive={setActive} />, results: <Results setActive={setActive} />, history: <Placeholder active="history" setActive={setActive} />, reports: <Placeholder active="reports" setActive={setActive} />, assistant: <Placeholder active="assistant" setActive={setActive} />, settings: <Placeholder active="settings" setActive={setActive} />, help: <Placeholder active="help" setActive={setActive} /> }[active] || <Dashboard setActive={setActive} />;
  return <div className="app-shell"><Sidebar active={active} setActive={setActive} mobileOpen={mobileOpen} setMobileOpen={setMobileOpen} /><div className="app-main"><Header onMenu={() => setMobileOpen(true)} onBrowse={() => setActive("browse")} onNotifications={() => setNotice(!notice)} />{notice && <div className="notification-pop"><span className="section-kicker">NOTIFICATIONS</span><strong>Workspace ready</strong><p>No new backend notifications yet.</p></div>}<main className="app-content">{content}</main><button className="exit-demo" onClick={onExit}>Back to landing</button></div></div>;
}

export default function App() {
  const [view, setView] = useState("landing"); const [authMode, setAuthMode] = useState("login");
  const openAuth = mode => { setAuthMode(mode); setView("auth"); };
  return <AnimatePresence mode="wait">{view === "landing" ? <motion.div key="landing" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><Landing onStart={() => setView("auth")} onLogin={() => openAuth("login")} onBrowse={() => setView("auth")} /></motion.div> : view === "auth" ? <motion.div key="auth" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><AuthShell mode={authMode} onModeChange={setAuthMode} onSuccess={() => setView("app")} onBack={() => setView("landing")} /></motion.div> : <motion.div key="app" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><AppShell onExit={() => setView("landing")} /></motion.div>}</AnimatePresence>;
}
